services:
  - type: web
    name: mailbrief
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: APP_NAME
        value: MailBrief
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: POLL_INTERVAL_SECONDS
        value: "60"
      - key: FREE_PLAN_MONTHLY_LIMIT
        value: "100"
      - key: POSTGRES_HOST
        fromDatabase:
          name: mailbrief-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: mailbrief-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: mailbrief-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: mailbrief-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: mailbrief-db
          property: database

databases:
  - name: mailbrief-db
    plan: free
